version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_HOST=fd98050b-4928-44e1-9536-66478313e9c5.us-west-1-0.aws.cloud.qdrant.io
      - QDRANT_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.3IUWpp8_yI-KDupXQzyBbkCnFDnP92hzWBO4uWqtq0M
      - QDRANT_PORT=6333
      - NEO4J_URI=neo4j+s://8f889fdf.databases.neo4j.io
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=BIcxg-LSb4Z9t8HGfJ6OJP1Ju1BzLrTfnGO4ZedDPjQ
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network

volumes:
  qdrant_data:

networks:
  app-network:
    driver: bridge 